name: Generate Snake

on:
  schedule:
    # Каждые 6 часов
    - cron: "0 */6 * * *"

  # Эта команда позволяет запускать действие автоматически из вкладки Actions.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        # Указываем использование Node.js 16.x
        with:
          submodules: true
          ref: v2

      - name: Set up Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Generate the snake
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: BakuEmilov
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Show the status of changes
        run: git status

      - name: Commit and push changes
        run: |
          git config --global user.name 'Your GitHub Username'
          git config --global user.email 'your-email@example.com'
          git add dist/github-contribution-grid-snake.gif dist/github-contribution-grid-snake.svg
          git commit -m "Update snake graph" || exit 0
          git push origin master

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


